name: Update GitHub Pages

on:
  push:
    branches: ['main']
    paths: ['./web']

  workflow_dispatch:

jobs:

  update:
    name: Update Github Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web
          publish_branch: gh-pages
          exclude_assets: .gitignore,tailwind.config.js,README.md,package.json,package-lock.json,node_modules
